### ISSUE TITLE
How to embed this font into a webpage?

### ISSUE THREAD

**Issue by jinch** [samvk/monorale-raleway-sober#4]
Does this font have a CSS file that we can link to in the head to use?

Along the lines of what was used for Raleway?
`<link href="https://raw.githubusercontent.com/h-ibaldo/Raleway_Fixed_Numerals/master/css/rawline.css" rel="stylesheet">` 

Or is this font just meant for self hosting?

**Comment by samvk** [comment]
https://raw.githubusercontent.com/samvk/monorale-raleway-sober/master/monorale.css

**Comment by jinch** [comment]
Thank you.

**Comment by jinch** [comment]
@samvk - question... i noticed in your CSS file you serve the font with [rawgit.com](https://rawgit.com/) CDN.

From what I understand, RawGit CDN is being phased out? Does this mean we should change the @font-face src to reference [https://raw.githubusercontent.com/...](https://raw.githubusercontent.com/samvk/monorale-raleway-sober/master/monorale.css) instead?
